### YamlMime:FAQ
metadata:
  title: Behandeln von Problemen bei Azure AD-Rollen mit Gruppenzuweisung - Azure Active Directory
  description: Hier finden Sie einige häufig gestellte Fragen und Tipps zur Problembehandlung in Bezug auf das Zuweisen von Rollen zu Gruppen in Azure Active Directory.
  services: active-directory
  author: rolyon
  manager: daveba
  ms.service: active-directory
  ms.workload: identity
  ms.subservice: roles
  ms.topic: article
  ms.date: 11/05/2020
  ms.author: rolyon
  ms.reviewer: vincesm
  ms.custom: it-pro
  ms.collection: M365-identity-device-management
  ms.openlocfilehash: c09bcdde3713f3ab93814cc67b23ded5cc49c17d
  ms.sourcegitcommit: 106f5c9fa5c6d3498dd1cfe63181a7ed4125ae6d
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 11/02/2021
  ms.locfileid: "131057132"
title: Behandeln von Problemen bei Azure AD-Rollen mit Gruppenzuweisung
summary: Nachfolgend sind einige häufig gestellte Fragen und Tipps zur Problembehandlung beim Zuweisen von Azure AD-Rollen zu Azure AD-Gruppen aufgeführt.
sections:
- name: Wird ignoriert.
  questions:
  - question: >
      Ich bin ein Gruppenadministrator, aber der Schalter „Azure AD-Rollen können der Gruppe zugewiesen werden“ wird mir nicht angezeigt.
    answer: >
      Nur Administratoren für privilegierte Rollen oder globale Administratoren können eine Gruppe erstellen, die zur Rollenzuweisung berechtigt ist. Nur Benutzern in diesen Rollen wird das Steuerelement angezeigt.
  - question: >
      Wer kann die Mitgliedschaft von Gruppen ändern, die Azure AD-Rollen zugewiesen sind?
    answer: >
      Standardmäßig können nur Administratoren für privilegierte Rollen und globale Administratoren die Mitgliedschaft in einer Gruppe mit Rollenzuweisung verwalten, Sie können jedoch die Verwaltung von Gruppen mit Rollenzuweisung delegieren, indem Sie Gruppenbesitzer hinzufügen.
  - question: >
      Ich bin ein Helpdesk-Administrator in meiner Organisation, aber ich kann das Kennwort eines Benutzers mit der Rolle „Verzeichnis lesen“ nicht aktualisieren. Was ist die Ursache?
    answer: >
      Der Benutzer hat die Rolle „Verzeichnis lesen“ möglicherweise über eine Gruppe erhalten, der Rollen zugewiesen werden können. Alle Mitglieder und Besitzer einer Gruppe, der Rollen zugewiesen werden können, sind geschützt. Nur Benutzer in der Rolle „Privilegierter Authentifizierungsadministrator“ oder „Globaler Administrator“ können Anmeldeinformationen für einen geschützten Benutzer zurücksetzen.
  - question: >
      Ich kann das Kennwort eines Benutzers nicht aktualisieren. Ihm ist keine Rolle mit erweiterten Berechtigungen zugewiesen. Warum geschieht das?
    answer: "Der Benutzer kann ein Besitzer einer Gruppe sein, der Rollen zugewiesen werden können. Besitzer von Gruppen mit Rollenzuweisung sind geschützt, um Rechteerweiterungen zu vermeiden. Hier ein Beispiel: Die Gruppe „Contoso_Security_Admins“ ist der Rolle „Sicherheitsadministrator“ zugewiesen, wobei Bob der Gruppenbesitzer und Alice die Kennwortadministratorin in der Organisation ist. Wäre dieser Schutz nicht vorhanden, könnte Alice die Anmeldeinformationen von Bob zurücksetzen und seine Identität übernehmen. Anschließend könnte Alice sich selbst oder andere Benutzer der Gruppe „Contoso_Security_Admins“ hinzufügen, um ein Sicherheitsadministrator in der Organisation zu werden. Wenn Sie herausfinden möchten, ob ein Benutzer ein Gruppenbesitzer ist, können Sie die Liste der im Besitz dieses Benutzers befindlichen Objekte abrufen und überprüfen, ob für eine der Gruppen „isAssignableToRole“ auf „true“ festgelegt ist. Wenn das der Fall ist, ist dieser Benutzer geschützt, und das Verhalten ist beabsichtigt. Informationen zum Abrufen von in Besitz befindlichen Objekten finden Sie in den folgenden Dokumentationen:\n\n- [Get-AzureADUserOwnedObject](/powershell/module/azuread/get-azureaduserownedobject)  \n- [Auflisten von ownedObjects](/graph/api/user-list-ownedobjects?tabs=http)\n"
  - question: "Kann ich eine Zugriffsüberprüfung für Gruppen erstellen, die Azure AD-Rollen zugewiesen werden können (insbesondere Gruppen, bei denen die Eigenschaft „isAssignableToRole“ auf „true“ festgelegt ist)?  \n"
    answer: >
      Ja, das ist möglich. Globale Administratoren und Administratoren für privilegierte Rollen können Zugriffsüberprüfungen von Gruppen erstellen, denen Rollen zugewiesen werden können.
  - question: >
      Kann ich ein Zugriffspaket erstellen und Gruppen hinzufügen, die Azure AD-Rollen zugewiesen werden können?
    answer: "Ja, das ist möglich. Der globale Administrator und der Benutzeradministrator haben die Möglichkeit, einem Zugriffspaket eine beliebige Gruppe hinzuzufügen. Für den globalen Administrator ändert sich nichts, doch bei den Rollenberechtigungen für den Benutzeradministrator gibt es eine geringfügige Änderung. Wenn Sie einem Zugriffspaket eine Gruppe mit Rollenzuweisung hinzufügen möchten, müssen Sie ein Benutzeradministrator und außerdem Besitzer der Gruppe mit Rollenzuweisung sein. In der folgenden Tabelle sind alle Rollen aufgeführt, die Zugriffspakete in Enterprise License Management erstellen können:\n\nAzure AD-Verzeichnisrolle | Berechtigungsverwaltungsrolle | Kann Sicherheitsgruppe hinzufügen\\* | Kann Microsoft 365-Gruppe hinzufügen\\* | Kann App hinzufügen | Kann SharePoint Online-Website hinzufügen\n----------------------- | --------------------------- | ----------------------- | ------------------------- | ----------- |  -----------------------------\nGlobaler Administrator | – | ✔️ | ✔️ | ✔️  | ✔️\nBenutzeradministrator  | –  | ✔️  | ✔️  | ✔️\nIntune-Administrator | Katalogbesitzer | ✔️  | ✔️  | &nbsp;  | &nbsp;\nExchange-Administrator  | Katalogbesitzer  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nTeams-Dienstadministrator | Katalogbesitzer  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nSharePoint-Administrator | Katalogbesitzer | &nbsp; | ✔️  | &nbsp;  | ✔️ \nAnwendungsadministrator | Katalogbesitzer  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nCloudanwendungsadministrator | Katalogbesitzer  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nBenutzer | Katalogbesitzer | Nur, wenn Gruppenbesitzer | Nur, wenn Gruppenbesitzer | Nur, wenn App-Besitzer  | &nbsp;\n\n\\*Der Gruppe kann keine Rolle zugewiesen werden, d. h. „isAssignableToRole“ = „false“. Wenn einer Gruppe Rollen zugewiesen werden können, muss die Person, die das Zugriffspaket erstellt, auch Besitzer der Gruppe mit Rollenzuweisung sein.\n"
  - question: >
      Ich kann unter „Zugewiesene Rollen“ die Option „Zuweisung entfernen“ nicht finden. Wie lösche ich die Rollenzuweisung für einen Benutzer?
    answer: >
      Diese Antwort trifft nur auf Azure AD Premium P1-Organisationen zu.


      1. Melden Sie sich beim [Azure-Portal](https://portal.azure.com) oder [Azure AD Admin Center](https://aad.portal.azure.com) an, und öffnen Sie **Azure Active Directory**.

      1. Wählen Sie Benutzer aus, und öffnen Sie ein Benutzerprofil.

      1. Wählen Sie **Zugewiesene Rollen** aus.

      1. Wählen Sie das Zahnradsymbol aus. Ein Bereich wird geöffnet, der die entsprechenden Informationen enthält. Neben direkten Zuweisungen wird eine Schaltfläche „Entfernen“ angezeigt. Zum Entfernen einer indirekten Rollenzuweisung entfernen Sie den Benutzer aus der Gruppe, der die Rolle zugewiesen wurde.
  - question: >
      Wie kann ich alle Gruppen anzeigen, denen Rollen zugewiesen werden können?
    answer: >
      Folgen Sie diesen Schritten:


      1. Melden Sie sich beim [Azure-Portal](https://portal.azure.com) oder [Azure AD Admin Center](https://aad.portal.azure.com) an, und öffnen Sie **Azure Active Directory**.

      1. Wählen Sie **Gruppen** > **Alle Gruppen** aus.

      1. Wählen Sie **Filter hinzufügen** aus.

      1. Filtern Sie nach **Rolle zuweisbar**.
  - question: >
      Wie kann ich feststellen, welche Rollen einem Prinzipal direkt und indirekt zugewiesen sind?
    answer: >
      Folgen Sie diesen Schritten:


      1. Melden Sie sich beim [Azure-Portal](https://portal.azure.com) oder [Azure AD Admin Center](https://aad.portal.azure.com) an, und öffnen Sie **Azure Active Directory**.

      1. Wählen Sie Benutzer aus, und öffnen Sie ein Benutzerprofil.

      1. Wählen Sie **Zugewiesene Rollen** aus, und gehen Sie dann folgendermaßen vor:

          - In Organisationen mit Azure AD Premium P1-Lizenz: Wählen Sie das Zahnradsymbol aus. Ein Bereich wird geöffnet, der die entsprechenden Informationen enthält.
          - In Organisationen mit Azure AD Premium P2-Lizenz: Informationen zu direkten und geerbten Lizenzen sind in der Spalte **Mitgliedschaft** enthalten.
  - question: "Warum wird das Erstellen einer neuen Gruppe für die Zuweisung zu einer Rolle erzwungen?  \n"
    answer: >
      Wenn Sie einer Rolle eine vorhandene Gruppe zuweisen, kann der vorhandene Gruppenbesitzer dieser Gruppe weitere Mitglieder hinzufügen, ohne dass die neuen Mitglieder wissen, dass sie über diese Rolle verfügen. Da Gruppen mit Rollenzuweisung über komplexe Berechtigungen verfügen, sind zu ihrem Schutz viele Einschränkungen vorhanden. Sie möchten keine Änderungen an der Gruppe, die für die Person, die die Gruppe verwaltet, überraschend wären.
additionalContent: "\n## <a name=\"next-steps\"></a>Nächste Schritte\n\n- [Verwenden von Cloudgruppen zum Verwalten von Rollenzuweisungen in Azure Active Directory (Vorschau)](groups-concept.md)\n- [Erstellen einer Gruppe, der Rollen zugeordnet werden können](groups-create-eligible.md)"
